### ISSUE TITLE
Version 5.0 release information

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#462]
:tada: ShopifySharp v5.0 has been released and published on nuget! You can install it with the dotnet CLI like this:

```sh
dotnet add package ShopifySharp --version 5.0.3
```

I've [written a guide here for migrating from v4 to v5](https://nozzlegear.com/shopify/shopifysharp-version-5-migration-guide). It doesn't cover every little change, but it does cover the big ones that are most likely to cause you issues when upgrading. If you think something is missing from this guide, let me know down below. 

[**ShopifySharp version 5 migration guide.**](https://nozzlegear.com/shopify/shopifysharp-version-5-migration-guide)

You can use this thread to ask about changes, report bugs, and let me know if a class or property you were previously using is missing.

# Paginated listing

The big change in this version is the new paginated listing operations that Shopify is now requiring. You can no longer request page 1, page 2, page 3, etc. of orders/customers/whatevers. You must use a special parameter they return during list operations to get the next page or the previous page. If you do not use that parameter, you will only ever get the first page of results. 

Since listing all customers/orders is a common question I get, here's how you do that going forward in ShopifySharp v5.0:

```cs
var allOrders = new List<Order>();
var service = new OrderService(domain, accessToken);
var list = await service.ListAsync(new OrderListFilter 
{ 
    Limit = 250 
});

while (true)
{
    allOrders.AddRange(list.Items);

    if (!list.HasNextPage)
    {
        break;
    }

    list = await service.ListAsync(list.GetNextPageFilter());
}
```

A couple important things to note about the above example:

- You must use the list result's `LinkHeader` to get a filter that will let you request the next page or the previous page. 
- The link header may be null, so you must check it before using it. This can happen e.g. if you're on page one and there's only one page total.
- The next page link and previous page link headers may specifically be null, even if the link header itself is not. This can happen e.g. when you're at the end of the list, there will be no next page link, but there will be a previous page link, and vice versa.
- **Once you've listed the first page, you cannot change any filter properties except for `Limit` and `Fields`.** Beyond the first page, Shopify will "remember" the filter properties you used previously and continue to apply them to all subsequent pages. If you want to make a change to one of those properties, you need to create a new filter and start over with the first page. 

# ~TODO~ Implemented

(**This section was tracking changes that needed to be made before the v5.0 release. They are now obsolete as v5.0 has been published.**)

Things to consider/implement before the full release is published:

- [x] What if we want to save the `PageInfo` parameter and then use it later, _outside_ of the `LinkHeader` class? Since `ListFilter` has an internal constructor, there's no way to reconstruct this class at a later point. We'd have to use the dedicated filter classes, but those contain properties that are not relevant to getting next/previous pages. 
  - Do we add a `ListFilter<T>.FromPageInfo(string pageInfo)`?
  - Use case: I want to show my users a list of their orders with a next/previous page link. I take the `PageInfo` value and store it in that link, then when they click it I use it to get either the next page or the previous page. 
- [x] Rename `PreviousLink.GetFollowingPageFilter()`? The name might be confusing when you're getting the _previous_ page, not the _following_ page. 
- [x] We need to manually set the `filter.Limit` each time we get the next/previous page filter from LinkHeader. Can we parse that out and set it automatically? Does `Limit` and `Fields` appear in the Link header returned by Shopify?
- [x] Better error parsing. ShopifySharp fails to parse error messages in may cases, instead returning a nearly useless `Response did not indicate success. 400 Bad Request` message instead. 
  - Example: creating a fulfillment without a `LocationId` value will return a message that looks like `{"error": "Fulfillment must set LocationId"}`. But ShopifySharp does not parse that and just returns the `400 Bad Request` message instead. 
- [x] Add filter class for `FulfillmentServiceService.ListAsync()`
- [x] Add filter class for `TransactionService.GetAsync()`?
- [x] Add tests for the Parameterizable class to ensure it serializes things like `IEnumerable<long>` properly. 
- [x] Update obsolete messages in ShopifySharp v4.x to note that ShopifySharp v5 is available.

There are a few other breaking changes, but the paginated list change is the major one. I'll update this post later on as I document the other changes.

**Comment by clement911** [comment]
The release package is likely not very usable.
I created a new [PR](https://github.com/nozzlegear/ShopifySharp/pull/463). Please release again when possible.

> What if we want to save the PageInfo parameter and then use it later, outside of the LinkHeader class?

Shopify has advised to not store the page info but your use case does make sense.
I made the constructor public: `public ListFilter(string pageInfo, int? limit)`

> Rename PreviousLink.GetFollowingPageFilter()?

I added two convenience methods on ListResult<T> to directly grab the next/previous page filter:

```
        public ListFilter<T> GetNextPageFilter(int? limit = null)
        {
            return LinkHeader?.NextLink?.GetFollowingPageFilter(limit);
        }

        public ListFilter<T> GetPreviousPageFilter(int? limit = null)
        {
            return LinkHeader?.PreviousLink?.GetFollowingPageFilter(limit);
        }
```

> We need to manually set the filter.Limit each time we get the next/previous page filter from LinkHeader. Can we parse that out and set it automatically? Does Limit and Fields appear in the Link header returned by Shopify?

I will change it so that Limit gets populated automatically (but can still be overridden).
For `Fields`, we would have to add it to the `ListFilter<T>` class?

**Comment by clement911** [comment]
Here is a more convenient way of paging through:

```
[Fact]
        public async Task Lists_Products_PageAll()
        {
            var svc = Fixture.Service;
            var list = await svc.ListAsync(new ProductListFilter { Limit = 5 });

            while (true)
            {
                Assert.True(list.Items.Any());
                list = await svc.ListAsync(list.GetNextPageFilter());
                if (!list.HasNextPage)
                    break;
            }
        }
```

**Comment by nozzlegear** [comment]
> I will change it so that Limit gets populated automatically (but can still be overridden).
> For `Fields`, we would have to add it to the `ListFilter<T>` class?

Good point, we would have to add it to the base class. `Fields` and `Limit` are the only things that can change once you've got a `PageInfo`, right? So even though I want to avoid having properties on a filter class if it's not applicable to a certain endpoint, we almost have no choice when it comes to fields. Otherwise the dev would have to do something like this:

```cs
var list = await service.ListAsync(new OrderListFilter
{
    Limit = 5,
    Fields = "id,title"
});

while (true)
{
    var nextPageFilter = list.GetNextPageFilter();
    var filter = new OrderListFilter
    {
        Limit = nextPageFilter.Limit,
        Fields = "id,title",
        PageInfo = nextPageFilter.PageInfo
    };
    var nextPage = await service.ListAsync(list.GetNextPageFilter());
    
    // ...
}
```

**Comment by nozzlegear** [comment]
I've pushed a few more changes, going to publish a new prerelease tonight. I've added `Fields` to the `ListFilter<T>` class and have the parsing logic attempting to populate it for next/previous page filters (this could use a test though). 

Unless anyone else has any suggestions or can spot any major issues, I can only think of one more thing I want to do quick before releasing v5: fixing the error message handling to pass the message returned by Shopify into the ShopifyException.

**Comment by nozzlegear** [comment]
Tests are passing! :tada:

**Comment by nozzlegear** [comment]
Prerelease version `5.0.0-b00360` published. Install with this command:

```sh
Install-Package ShopifySharp -Version 5.0.0-b00360
```

**Comment by natezhangjbhifi** [comment]
`published_status` is missing in `ProductListFilter`

**Comment by clement911** [comment]
That is fantastic. Thank you @nozzlegear for your hard work. It's much appreciated!

I hope people can start testing v5 as a thank you. I'll be doing that asap.

**Comment by nozzlegear** [comment]
Good catch @natezhangjbhifi! I've published a new version that adds that and a couple other properties which were missing on `ProductListFilter`. Should be available in prerelease `5.0.0-b00363` within the next 20 minutes.

```sh
dotnet add package ShopifySharp --version 5.0.0-b00363
```

**Comment by nozzlegear** [comment]
Published `5.0.0-b00365` earlier this evening. This one contains changes to the way ShopifyException messages are created; they should be much more useful now (I hope). In most cases, the exception messages will now contain both the status code Shopify returned, _plus_ any error message Shopify returned. There were several cases where the v4 package would fail to parse a useful error message and instead use something generic like `"Response did not indicate success, server returned 500 Internal Server Error"`.

Examples of the new exception messages:

```
(429 Too Many Requests) rate_limit: Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service.

(422 Unprocessable Entity) order: Tax lines must be associated with either order or line item but not both

(400 Bad Request) order: Required parameter missing or invalid
```

There are a couple of cases where the package will fall back to a more generic message: A) if the response does not contain valid JSON; B) if the response does not contain a JSON error message matching one of five known formats; C) if the response's content-type header doesn't indicate it contains JSON. 

I've got just a couple small changes left to make (found a couple of list methods that still need filter classes), and then I'll publish! I'm looking to do that either Saturday or Sunday.

**Comment by clement911** [comment]
Good stuff.

Why are you not parsing the error message when code == 429?
Currently the message is hard coded to 'Exceeded 2 calls per second for api client...' but Shopify has been introducing additional limits in recent months, such as the daily variant creation limit and order creation limit for dev stores.
It would be useful to the know the exact message to understand what limit was breached.

**Comment by clement911** [comment]
Actually I think paging should be like this:

```
public async Task Lists_Products_PageAll()
        {
            var svc = Fixture.Service;
            var list = await svc.ListAsync(new ProductListFilter { Limit = 5 });

            while (true)
            {
                //processList(list.Items);
                if (!list.HasNextPage)
                    break;
                list = await svc.ListAsync(list.GetNextPageFilter());
            }
        }
```

**Comment by nozzlegear** [comment]
> Good stuff.
> 
> Why are you not parsing the error message when code == 429?
> Currently the message is hard coded to 'Exceeded 2 calls per second for api client...' but Shopify has been introducing additional limits in recent months, such as the daily variant creation limit and order creation limit for dev stores.
> It would be useful to the know the exact message to understand what limit was breached.

I can't remember why the message is hard coded, but it looks like it's always been that way since the introduction of the `ShopifyRateLimitException`. Perhaps it was one of those few errors that Shopify returned HTML or text instead of JSON. I'll debug today and see what it's returning now.

**Comment by nozzlegear** [comment]
Changed in `5.0.0-b00366`, the service will now read the rate limit error message returned by Shopify. It will only default to a generic "rate limit exceeded" message if it can't read one.

**Comment by nozzlegear** [comment]
ShopifySharp version 5.0 has been published on nuget! The update is now officially available, big thank you to @clement911 and everyone else who has contributed or offered feedback for this new release! 

I’m working on a migration guide right now and will publish it either Monday or Tuesday. Please let me know if you run into any issues with v5.0.

**Comment by clement911** [comment]
Great news!

I completed some manual testing and 2 bugs.
PR for fixes: https://github.com/nozzlegear/ShopifySharp/pull/465

Beware in particular that `RecurringChargeService.ActivateAsync` has a typo bug.

**Comment by clement911** [comment]
Given that ShopifySharp v5 targets 2019-10, your webhook app settings should be updated accordingly to match this version.

**Comment by natezhangjbhifi** [comment]
Hi @nozzlegear 
`published_status` , `fields` and `presentment_currencies` you added into the prerelease appear to be missing in `ProductListFilter` in the latest stable release again.

**Comment by mark-jeanswhse** [comment]
Hi @nozzlegear 
Testing v5 and noticed that `PriceRuleDiscountCodeListFilter` is missing from `ShopifySharp.Filters`. Can we add this to a future release?

**Comment by SeanoNET** [comment]
Thanks @nozzlegear @clement911  and others on all your hard work in getting v5 released!

I have some questions around parsing the endpoint specific list filters into the requests after the initial request.

Your example above (I understand might be outdated in v5.0.1) wouldn't included the `FulfillmentStatus = "any"` in the subsequent requests after the initial request. Unless i am missing something?

```csharp
var service = new OrderService(shopDomain, accessToken);
var allOrders = new List<Order>();
ListFilter<Order> filter = new OrderListFilter
{
  // Get 75 orders at a time
  Limit = 75,
  FulfillmentStatus = "any"
};

while (true) 
{
  var orders = await service.ListAsync(filter);
  
  allOrders.AddRange(orders.Items);

  if (orders.LinkHeader?.NextLink != null)
  {
	var newFilter = orders.LinkHeader.NextLink.GetFollowingPageFilter();
    // NOTE: For now, you must set the limit and fields property for further page filters manually.
    newFilter.Limit = filter.Limit; 
    // Set the filter to the following page filter, which will grab the next page.
    // Failure to do this will result in an infinite loop as the Shopify API returns the first page over and over
    filter = newFilter; 
  }
  else 
  {
    break;
  }
}
```

The pageInfo is read only so i can't populate the `PageInfo` in my `OrderListFilter` and also can't populate the order related filters in the `result.GetNextPageFilter()` sinces it's the base `ListResult(Of T)` class.

```vbnet
            Dim filter As New OrderListFilter
            filter.Limit = 50
            filter.Status = "open"
            filter.FinancialStatus = "authorized,paid,partially_paid"
            filter.FulfillmentStatus = "unshipped"

            Dim result As ListResult(Of ShopifySharp.Order) = Nothing

            While True
                If IsNothing(result) Then
                    result = orderService.ListAsync(filter).Result
                Else
                    result = orderService.ListAsync(result.GetNextPageFilter()).Result
                End If

                'Process result

                If Not result.HasNextPage Then
                    Exit While
                End If
            End While
```

Or am i completely missing the point with Shopify's new pagination changes and Shopify does in fact know the filter options from the initial request since we are using a `PageInfo` each request?

**Comment by clement911** [comment]
The `page_info` will 'remember' the filters that you applied during the first request.
As you paginate, you can only change the `limit` and `fields`.

See https://shopify.dev/tutorials/make-paginated-requests-to-rest-admin-api

![image](https://user-images.githubusercontent.com/3426504/75759009-25f9d000-5d35-11ea-8a5b-d73c5890a510.png)


Btw, a better way of paginating can be found here: https://github.com/nozzlegear/ShopifySharp/issues/462#issuecomment-592939273

**Comment by SeanoNET** [comment]
ah, that makes sense, thanks for clarifying.

I'll be sure to check that out.

>Btw, a better way of paginating can be found here: #462 (comment)

**Comment by clement911** [comment]
We are now running our app in prod with Shopify v5.1!
So far so good and it feels great to be up to date.
For others updating, make sure you also take a look at your API health dashboard: https://shopify.dev/concepts/about-apis/versioning/api-health
It's very useful!

@nozzlegear , will you create a new branch for 2020-01?

**Comment by davidkdb** [comment]
Cannot find the abandoned checkouts service in version 5.0

In case it is the CheckOutService it's missing almost all the methods and filters, and cannot be used.

It should be very similar to OrderService

**Comment by nozzlegear** [comment]
> Hi @nozzlegear
> Testing v5 and noticed that `PriceRuleDiscountCodeListFilter` is missing from `ShopifySharp.Filters`. Can we add this to a future release?

@mark-jeanswhse Done! Published in 5.0.2. 

> Hi @nozzlegear
> `published_status` , `fields` and `presentment_currencies` you added into the prerelease appear to be missing in `ProductListFilter` in the latest stable release again.

@natezhangjbhifi It looks to me like these are still in the latest release! I'm not sure why they wouldn't be showing up for you again, are you sure it's the `ProductListFilter` that doesn't have them? Maybe you're accidentally using the `ProductCountFilter`?

> Cannot find the abandoned checkouts service in version 5
> 
> In case it is the CheckOutService it's missing almost all the methods and filters, and cannot be used.
> 
> It should be very similar to OrderService

Added missing methods in 5.0.2 (#468)

**Comment by nozzlegear** [comment]
> @nozzlegear , will you create a new branch for 2020-01?

@clement911 done! `2020-01` branch has been created.

**Comment by natezhangjbhifi** [comment]
> @natezhangjbhifi It looks to me like these are still in the latest release! I'm not sure why they wouldn't be showing up for you again, are you sure it's the `ProductListFilter` that doesn't have them? Maybe you're accidentally using the `ProductCountFilter`?
> 

Sorry, my Visual Studio is playing up, thanks for checking, all good.

**Comment by davidkdb** [comment]
Hi, getting an error during run:
Message = "Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x8...
=== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///L:/Div/ProdGroupyTest/TestForms/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : ShopifySharp, Version=5.0.3.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: L:\Div\ProdGroupyTest\TestForms\bin\Debug\TestForms.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///L:/Div/ProdGroupyTest/TestForms/bin/Debug/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

I have the latest Newtonsoft (12.0.3) package installed in my project, and project is Net Standard 2.0

**Comment by SeanoNET** [comment]
@davidkdb ShopifySharp uses Newtonsoft v10.0.1 - it wont be able to resolve to a 12.x version reference.

https://github.com/nozzlegear/ShopifySharp/blob/3d41f8277bb4943eb51134c7352377f32eb61761/ShopifySharp/ShopifySharp.csproj#L19

Try running a restore or download Newtonsoft v10.0.1 from nuget.

**Comment by davidkdb** [comment]
I'm using GraphQL.Client also and it requires Newtonsoft 12.0.3

**Comment by nozzlegear** [comment]
Interesting. In theory I have no issue with updating the dependency, but would that then affect people who have some other package that requires newtonsoft.json 10x or 11x?

**Comment by nozzlegear** [comment]
Also wasn't there a new built-in JSON serializer/deserializer in one of the newer dotnet standards? It would be nice to eventually get rid of external dependencies altogether.

**Comment by davidkdb** [comment]
Actually GraphQL (not GraphQL client) depends on >=10.0.0.3, and works perfectly with 12.0.3 and so could ShopifySharp.

And anyways it's time to upgrade the dependencies when updating ShopifySharp to a major new version. Things with dependencies will not get better in time

> Also wasn't there a new built-in JSON serializer/deserializer in one of the newer dotnet standards? It would be nice to eventually get rid of external dependencies altogether.

Yes, you could, but Newtonsoft is regarded by far the best and fastest. That's why most others also use it

**Comment by davidkdb** [comment]
Actually maybe not a bad idea to convert to system.text.json.

It's faster, but less flexible than Newtonsoft. Seen some very good reviews. Actually the man behind Newtonsoft is used by MS in the project.

But it requires framework 4.,6.1 or higher

**Comment by Fashionepaul** [comment]
Thankyou for releasing 5.0.  I have manged to update my product and order lists without any problems.  Aiming to go live next week after some more testing.

**Comment by davidkdb** [comment]
How can I see what's been changed in new build ? (5.0.4)

**Comment by nozzlegear** [comment]
Typically I do a new release for each publish which includes a changelog. I’m on mobile right now and can’t do that at the moment. There’s a way to see the line-by-line code changes with GitHub though, you can compare the latest commit to the commit tagged as 5.0.3.

**Comment by nozzlegear** [comment]
[5.0.4 release notes](https://github.com/nozzlegear/ShopifySharp/releases/tag/5.0.4-release)

**Comment by ThatBrianK** [comment]
Hi there, I love this library and truly appreciate everyone's work on this!
I noticed that under ProductVariant, the field InventoryQuantity is still allowing a value to be passed in, which shopify will not allow. Perhaps this could be marked as readonly? 
it's too bad this field was deprecated though, since now all of my initial creation of shopify products will take twice as long! since it will require posting the product and then making a separate call to set the inventory level.

**Comment by nozzlegear** [comment]
@ThatBrianK I might be able to make it readonly. I can't remember if that interferes with deserialization or not. Is it causing problems for you right now? I think if you set it to null it might work around the errors it causes.

**Comment by somatech-uk** [comment]
Is there any reason why the services don't implement an interface that contains ListAsync? - This would allow the while loop to retrieve all items to be made into a generic method and not have the code duplicated for each service.

**Comment by ThatBrianK** [comment]
It only temporarily caused a problem because I didn't realize that Shopify was no longer allowing writes to that field. In fact, it even means something different now - it's the total quantity of the variant across all locations. Once I realized I couldn't set it, i just removed the call and implemented new functionality to manually set the quantity using InventoryLevel. I could see someone else making the same mistake I did when porting the code, but it's really not a big deal. I imagine if someone was just starting out with Shopify they wouldn't have gotten used to how it used to work (with only one location).

> @ThatBrianK I might be able to make it readonly. I can't remember if that interferes with deserialization or not. Is it causing problems for you right now? I think if you set it to null before using `ProductService.UpdateAsync` it might work around the errors it causes.

**Comment by davidkdb** [comment]
Any news on the Newtonsoft incompatibility ? It's big problem when using both ShopifySharp and GraphQL (using GraphQL.Client)

**Comment by nozzlegear** [comment]
@davidkdb Sorry about that, I took your last message to mean that you were able to get it working without needing an update to the latest version. I'll try to do an update within the next couple of days to bump the dependency.

**Comment by nozzlegear** [comment]
I've [written a guide here to help with the migration from v4 to v5](https://nozzlegear.com/shopify/shopifysharp-version-5-migration-guide). It doesn't cover everything, just the major bits that are most likely to cause issues.

**Comment by nozzlegear** [comment]
Quick update for everyone, it looks like Shopify has delayed the mandatory API migration due to COVID-19. You now have until July 1st to update, delayed from April 1st. Here's the email I got:

>Hello there,
>
>With the evolving concerns around COVID-19’s impact on communities around the world, we know that partners and merchants are making adjustments to continue running their businesses smoothly. That’s why we’ve decided to postpone the April 1 version removal to July 1, 2020.
>
>What does this change mean?
>This means that you have additional time until July 1 to update your apps to account for changes in both 2019-07 and 2019-10 API versions. Specifically, the move from page to cursor based pagination will come into effect for all endpoints on July 1, which should simplify the migration process for your apps.
>
>To see which deprecated API calls your apps are making, check out the API Health report on the Partner Dashboard.
>
>For those of you who’ve put in the time and energy to update already, we want to say thank you for your diligence and understanding in the extension—your efforts haven’t gone to waste.
>
>If you have any questions, chat with us in the API forums or the Support section of the Partner Dashboard.
>
>Thank you,
>Shopify Apps Team

**Comment by ishahrier** [comment]
> Quick update for everyone, it looks like Shopify has delayed the mandatory API migration due to COVID-19. You now have until July 1st to update, delayed from April 1st. Here's the email I got:
> 
> > Hello there,
> > With the evolving concerns around COVID-19’s impact on communities around the world, we know that partners and merchants are making adjustments to continue running their businesses smoothly. That’s why we’ve decided to postpone the April 1 version removal to July 1, 2020.
> > What does this change mean?
> > This means that you have additional time until July 1 to update your apps to account for changes in both 2019-07 and 2019-10 API versions. Specifically, the move from page to cursor based pagination will come into effect for all endpoints on July 1, which should simplify the migration process for your apps.
> > To see which deprecated API calls your apps are making, check out the API Health report on the Partner Dashboard.
> > For those of you who’ve put in the time and energy to update already, we want to say thank you for your diligence and understanding in the extension—your efforts haven’t gone to waste.
> > If you have any questions, chat with us in the API forums or the Support section of the Partner Dashboard.
> > Thank you,
> > Shopify Apps Team

thanks for sharing the news!!!

**Comment by j3pup** [comment]
Hey guys, love your tool.  Just noticed ListAsync(orderListFilter);   Doesn't seem to work with any more than 1 id in the array.  Maybe it's user error, but wanted to let you know.
                  long[] values = new long[] {2710221979809, 2710223650977, 2710223880353};
                        OrderListFilter orderListFilter = new OrderListFilter();
                        orderListFilter.Limit = 250;
                        orderListFilter.Ids = values;

**Comment by htsan** [comment]
Hello,
Thank you for all your team's hard work. I'm trying to use the new version 5.8. It looks very good. Just notice that PaymentDetail in ShopifySharp.Order is missing. Could you please add this for the next release.
Thank you so much.
Really appreciate your work.

**Comment by nodrogyad** [comment]
Any word on NewtonSoft v12?  Looking at the csproj file, it looks like the update to the newer version never happened...
